### ISSUE TITLE
获取成绩的网址是不能用了吗，前几天还好好的，现在404了

### ISSUE THREAD

**Issue by Jolly23** [realityone/GetCet#4]
查询准考证号还能用，但是获取成绩不行了：

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>

<h1>Not Found</h1>

<p>The requested URL /findscore was not found on this server.</p>

</body></html>

**Comment by NullYing** [comment]
防火墙封了你ip

**Comment by ttimasdf** [comment]
不不不，99的API地址改了，而且强制上了https
